from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookViewSet  # Assuming BookViewSet is the correct ViewSet

router = DefaultRouter()
router.register(
    r"books", BookViewSet
)  # Registering BookViewSet for the 'books' endpoint

urlpatterns = [
    path("", include(router.urls)),  # Including the URLs generated by the router
]
